name: Docker Image CI

on:
  release:
    types: [created]

jobs:

  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: add release version to envs
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
#       - name: Login to DockerHub
#         uses: docker/login-action@v1 
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.RELEASE_VERSION }}

#       - uses: docker/setup-buildx-action@v1
#         id: buildx
#         with:
#           install: true

#       - name: Build
#         run: |
#           echo "docker build --tag ghcr.io/${{ github.repository }}:$RELEASE_VERSION ."
          
#           docker build . --tag 
